### ISSUE TITLE
CDN for resting-state fMRI

### ISSUE THREAD

**Issue by arosas5** [xuefeicao/CDN#3]
Hello,

I am currently working with resting-state fMRI data and would like to implement your CDN toolbox however I see that the code is meant for task-related fMRI. Is there an option to use a blank stimulus in order to run this analysis for resting-state fMRI? From your Causal Dynamic Network Modeling paper (https://doi.org/10.3389/fnins.2019.00127), it was mentioned that it is possible with a simple modification to the toolbox to allow the for analyses to be performed on resting-state fMRI. Thank you!

Best 

Alberto

**Comment by xuefeicao** [comment]
Hi, you might want to fix B and C as 0 in the code for each optimization loop.
